version: "3"

services:
  server:
    build:
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    container_name: rag
    image: "rag:1.0.0"
    environment:
      PORT: 8000
    env_file:
      - .env
    volumes:
      - data
