
server:
  env_name: ${APP_ENV:dev}
  port: ${PORT:8000}

cors:
  enabled: ${CORS_ENABLED:false}
  allow_credentials: ${CORS_ALLOW_CREDENTIALS:false}
  allow_origins: ${CORS_ALLOW_ORIGINS:["*"]}
  allow_origin_regex: ${CORS_ALLOW_ORIGIN_REGEX:["*"]}
  allow_methods: ${CORS_ALLOW_METHODS:["*"]}
  allow_headers: ${CORS_ALLOW_HEADERS:["*"]}

azopenai:
  api_key: ${AZ_OPENAI_API_KEY:}
  azure_endpoint: ${AZ_OPENAI_ENDPOINT:}
  api_version: ${AZ_OPENAI_API_VERSION:2023-05-15}
  embedding_model: ${AZ_OPENAI_EMBEDDING_MODEL:text-embedding-ada-002}
  llm_deployment_name: ${AZ_OPENAI_LLM_DEPLOYMENT_NAME:}
  llm_model: ${AZ_OPENAI_LLM_DEPLOYMENT_NAME:gpt-35-turbo}
  temperature: ${AZ_OPENAI_TEMPERATURE:0.1}

vectorstore:
  database: chroma